config/routes.rb
Rails.application.routes.draw do
  resources :crews
  resources :concerts
  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "concerts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :group
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :concerts, dependent: :destroy
    has_many :crews, dependent: :destroy
    enum band_type: [:Boyband, :Girlband, :Band]


    def to_s #Nos permite pasar a string
        name
    end 

    def total_concerts #cuenta los conciertos
        concerts.where(group_id: id).count
    end

    def attendance #asistentes al concierto por grupo
        concerts.pluck(:attendance).sum
    end


    def last_concert #Ultimo concierto en el mes
        if concerts.count > 0
            concerts.order(concert_date: :asc).last.concert_date
        else
            "No concert date"
        end
    end

    def max_attendence #max de personas en un concierto
        concerts.pluck(:attendance).max
    end

    def max_duration #duracion max de un concierto
        concerts.pluck(:duration).max
    end
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.eager_load(:group) #disminuye las consultas en el index (N+1 query)
    @groups = Group.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    @groups = Group.all
  end

  # GET /concerts/1/edit
  def edit
    @groups = Group.all
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)
    @groups = Group.all

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:attendance, :duration, :concert_date, :group_id)
    end
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: %i[ show edit update destroy ]

  # GET /crews or /crews.json
  def index
    @crews = Crew.all
  end

  # GET /crews/1 or /crews/1.json
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
    @groups = Group.all 
  end

  # GET /crews/1/edit
  def edit
    @groups = Group.all 
  end

  # POST /crews or /crews.json
  def create
    @crew = Crew.new(crew_params)
    @groups = Group.all 

    respond_to do |format|
      if @crew.save
        format.html { redirect_to @crew, notice: "Crew was successfully created." }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1 or /crews/1.json
  def update
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to @crew, notice: "Crew was successfully updated." }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1 or /crews/1.json
  def destroy
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to crews_url, notice: "Crew was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(:name, :group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]
  

  # GET /groups or /groups.json
  def index
    @groups = Group.all
    @concerts = Concert.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @concerts = Concert.all
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @concerts = Concert.all

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :members, :debut, :band_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attendance %>
    <%= form.number_field :attendance, id: :concert_attendance %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :concert_duration %>
  </div>

  <div class="field">
    <%= form.label :concert_date %>
    <%= form.date_select :concert_date, id: :concert_concert_date %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.collection_select :group_id, @groups, :id, :name%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table>
  <thead>
    <tr>
      <th>Attendance</th>
      <th>Duration</th>
      <th>Concert date</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.attendance %></td>
        <td><%= concert.duration %></td>
        <td><%= concert.concert_date %></td>
        <td><%= concert.group %></td>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attendance:</strong>
  <%= @concert.attendance %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @concert.duration %>
</p>

<p>
  <strong>Concert date:</strong>
  <%= @concert.concert_date %>
</p>

<p>
  <strong>Group:</strong>
  <%= @concert.group %>
</p>

<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/crews/_form.html.erb
<%= form_with(model: crew, local: true) do |form| %>
  <% if crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
      <% crew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :crew_name %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.collection_select :group_id, @groups, :id, :name%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

app/views/crews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.name %></td>
        <td><%= crew.group %></td>
        <td><%= link_to 'Show', crew %></td>
        <td><%= link_to 'Edit', edit_crew_path(crew) %></td>
        <td><%= link_to 'Destroy', crew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crew', new_crew_path %>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Back', crews_path %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crew.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @crew.group %>
</p>

<%= link_to 'Edit', edit_crew_path(@crew) %> |
<%= link_to 'Back', crews_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :group_name %>
  </div>

  <div class="field">
    <%= form.label :members %>
    <%= form.number_field :members, id: :group_members %>
  </div>

  <div class="field">
    <%= form.label :debut %>
    <%= form.date_select :debut, id: :group_debut %>
  </div>

  <div class="field">
    <%= form.label :band_type %>
    <%= form.select :band_type, Group.band_types.keys %>

  </div>

  <div class="field">
    <%= form.fields_for :crews do |crew_form|%>
      <%= crew_form.label :name, 'Member Name' %>
      <%= crew_form.text_field :name %>
    <%end%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Members</th>
      <th>Debut</th>
      <th>Band Type</th>
      <th>Total Concerts</th>
      <th>Attendance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.members %></td>
        <td><%= group.debut %></td>
        <td><%= group.band_type %></td>
        <td><%= group.total_concerts %></td>
        <td><%= group.attendance %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Members:</strong>
  <%= @group.members %>
</p>

<p>
  <strong>Debut:</strong>
  <%= @group.debut %>
</p>

<p>
  <strong>Band Type:</strong>
  <%= @group.band_type %>
</p>


<strong>Last Concert:</strong>
  <% if @group.last_concert != "No concert date" %>
    <%= @group.last_concert.strftime("%Y-%B-%A") %>
  <%end%>
</p>

<p>
    <strong>Max Attendance:</strong>
    <%= @group.max_attendence %> personas
</p>

<p>
    <strong>Concert Duration:</strong>
    <%= @group.max_duration %> horas
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppProdEvent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>